### PR TITLE
[WIP] Test the Ruby Spec suite on Windows with AppVeyor

### PR DESCRIPTION
**Pull request by eregon**
@unak This is what I was talking about, I think we should merge this once specs pass on Windows, otherwise it might be confusing for other contributions to have a failing CI.

Results are at https://ci.appveyor.com/project/eregon/spec/history.

### CODE REVIEW

**Comment by unak** [comment]
@eregon Sorry, I cannot explain in English well. I want to forgive me if you feel that I'm too blunt.

I've also found that Windows needs this patch.
But, the reason why this patch is necessary is that some test cases lack cleaning up child processes.
On Windows there are many many failed test cases of `Process`.
We should fix them instead of removing `Process.waitall`.

**Comment by eregon** [comment]
@unak I reverted c7a99a60a25b3ecda8ac1f2dc504a73095dd1754.
It seems indeed the CI hangs on that one, so some subprocess must leak and hang before that spec is run.

I introduced a check for leaking subprocesses in mspec: https://github.com/ruby/mspec/commit/8c048530d53879c825ffb4588f65289e22e1ea77, and fixed a few specs that were leaking.
It can be run with
```
CHECK_LEAKS=true path/to/mspec ...
```
I am not sure that runs well on Windows though, I need to try.

**Comment by eregon** [comment]
It seems the first spec of `Process#kill` creates a subprocess which is never killed.
```
...
[00:01:05] Process.kill
[00:01:05] - raises an ArgumentError for unknown signals
```

I'd guess `SIGTERM` is unsupported on Windows and `core/process/fixtures/kill.rb` is never killed.
Probably most of the `Process.kill` specs should be skipped on Windows since it's only supported for a few signals.
@unak What do you think?

**Comment by unak** [comment]
I think we should use `SIGKILL` instead of `SIGTERM`.

**Comment by vais** [comment]
Yes, only straight up kill (9) works on Windows

**Comment by eregon** [comment]
But then the signal handler is not triggered and it doesn't write to the
file to acknowledge. Would a trap on SIGINT/Ctrl+C work instead?

**Comment by vais** [comment]
@eregon I'm not sure I fully understand the problem, but yes, `trap(INT)` works on Windows to hijack `Ctrl-C` and do whatever (I had some experience with it in [my restart script here](https://github.com/vais/restart/blob/master/lib/restart.rb#L144) - in that case I am doing something funky with win32 api to generate the `Ctrl-C` event instead of sending it to the process via `kill` though, but that's for other reasons - it has the effect on all processes running in the shell, which is what I need there.)

**Comment by eregon** [comment]
I tried to trap Ctrl+C, but then that shows in the output:
`Terminate batch job (Y/N)?`
which makes the CI hang :disappointed: , and I found no way to disable that confirmation.
So the current fix is to just disable the Signalizer as it cannot work as-is on Windows.

**Comment by vais** [comment]
@eregon could you paste some links to the problematic code so I can take a crack at it as well?

**Comment by eregon** [comment]
@vais https://github.com/eregon/rubyspec/commit/c1e9b5807b87ea34d819ddb4a9f319068e241e30 is my attempt to try to test trap behavior on Windows.
If `Process.kill("SIGINT", pid)` would trigger the registired trap handler without asking for user confirmation, it seems we could run those spec on Windows as well. If not it's probably fine to exclude them and maybe have a few Windows-specific ones.

**Comment by eregon** [comment]
I pushed this to master, closing.

**Pull request closed without merging**
