### PR TITLE
Add `.rubocop.yml`

### PR DESCRIPTION
**Pull request by pocke**
Ref: https://github.com/ruby/spec/pull/443#issuecomment-307031971

I added `.rubocop.yml` to prevent some problem like #443 .

In the configuration:

- Style cops(rules) are disabled.
  - For example: indentation, spacing and empty lines
- Lint cops are enabled.
  - For example: duplicated method
- `Lint/Void` is disabled.
  - Because the cop registers too many false positives to `.should == something`

However, with the configuration file, too many warnings exist in this repository. And the warnings has many false positives.

For example:

```ruby
  # In library/bigdecimal/lte_spec.rb:45
  # The warning is a noise for this spec, but it makes sense in other place.
  (two <= two).should == true # => W: Lint/UselessComparison: Comparison of something with itself detected.
```

So, I propose using SideCI with Abyssinian mode to run RuboCop.
https://blog.sideci.com/fighting-false-detections-with-lint-tools-in-abyssinian-mode-7f7bbcb45c48
In SideCI, we can ignore warnings if the warning is false positive.

### CODE REVIEW

**Comment by eregon** [comment]
I ran it locally and got:
```
4301 files inspected, 1411 offenses detected
```
That's a lot.
I think we might we want to give up on some cops which produce too many false positive, filtering by hand seems too much work.
Interesting pointer about SideCI though, I did not know about that.

I ran `rubocop --auto-gen-config` and got https://gist.github.com/eregon/bab385dd00b8a4731d115c991d920e9e
which notably includes `Offense count` per cop.

I'll give some thought to this and experiment with it, thanks for the PR!

**Comment by pocke** [comment]
Thanks. I added `.rubocop_todo.yml` 👍 


```bash
$ rubocop 
Inspecting 4290 files
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

4290 files inspected, no offenses detected
```

**Comment by enebo** [comment]
@eregon I am hoping rubocop is not required to commit to this project.  I think rubocop can catch mistakes but with ruby/spec it seems the false positive aspect will make this annoying (e.g. extra impedance to add exceptions for something reasonably normal for this sort of application).

**Comment by eregon** [comment]
@enebo Yes, I agree we need to be very careful so it's not annoying.
For instance, I don't plan to add say a string literal style cop as that would be too annoying for little gains.
If too many exceptions are needed for a cop I'd rather disable it, so in the end get something that might help catch a few mistakes but more importantly is not an overhead for the development of ruby/spec.

**Comment by pocke** [comment]
I think we can ignore almost false positives just by running `rubocop --auto-gen-config`. The command generates `.rubocop_todo.yml`, and ignoring by the file is reasonable to me.

**Comment by deivid-rodriguez** [comment]
I think this is a good use case for the

```
AllCops:
  DisabledByDefault: true
```

configuration!

**Comment by eregon** [comment]
I fixed a few alignment issues and disabled a few cops which do not work well with ruby/spec.
I added RuboCop in this CI too so to know when a new offense is detected.
Based on new offenses, we can refine the `.rubocop_todo.yml`.
Thank you for your contribution!

**Pull request merged**
