### PR TITLE
Merge specs of UNIXSocket.pair and UNIXSocket.socketpair into a shared spec

### PR DESCRIPTION
**Pull request by herwinw**
The methods are aliases, so we probably shouldn't have two separate specs hanging around.

### CODE REVIEW

**Comment by herwinw** [comment]
This is a second attempt at  #1131, because I've had commit permissions for 1 day and I already screwed things up by merging the wrong branch

**Comment by eregon** [comment]
I'm confused, this seems to have the same commits as #1131 which is merged (and looks alright and CI passed).

**Comment by andrykonchin** [comment]
It seems commits in #1131 were removed from the master branch.

**Comment by andrykonchin** [comment]
Thank you!

**Pull request merged**
