### PR TITLE
Each spec

### PR DESCRIPTION
**Pull request by BurdetteLamar**

### CODE REVIEW

**Comment by eregon** [comment]
Could you remove the first 2 commits of this PR, since they are already in https://github.com/ruby/spec/pull/694?

**Comment by BurdetteLamar** [comment]
I'll admit that I'm on unfamiliar ground here.  In the past I've worked alone in my own Github projects.  I want to be helpful here, and not a nuisance.

I don't know how to remove those commits from the PR; can you advise?

Also, would it be better to have everything in one branch?

**Comment by BurdetteLamar** [comment]
eregon, I'm going to close 694-6 and start over.

It seems to be impractical to "stack" PRs in GitHub.  I'll put up PRs one at a time from now on.

**Comment by eregon** [comment]
> I don't know how to remove those commits from the PR; can you advise?

One way is to use `git rebase -i`, that's convenient to remove, reorder, alter commits, etc.

In general, each PR should have its own commits, i.e., no 2 PRs should have the same commits. If they depend on each other, than just make it clear which one should be merged first. Once it's merged, you could rebase the second PR and common commits would automatically be removed.

**Pull request closed without merging**
