### PR TITLE
DidYouMean specs for ruby 2.3

### PR DESCRIPTION
**Pull request by mjago**
with reference to issue #175

### CODE REVIEW

**Comment by eregon** [comment]
Nice!
It's a bit strange that ruby trunk does not pass those specs, maybe an issue with Travis' MRI build?

**Comment by mjago** [comment]
@eregon Yes I thought the same - did_you_mean doesn't seem activated on travis trunk.
I briefly checked out did_you_mean gem's repo last night [github](https://github.com/yuki24/did_you_mean) and there may be some dependency issue regarding travis / trunk and a dependency of did_you_mean gem. I can look into it. 
In the mean time it helps resolve the #175 issue with the current guard I guess?

**Comment by eregon** [comment]
@mjago It works locally for me on my ruby trunk, I think Travis uses RVM to package ruby-head and that seems the cause of the problem.
I am pondering whether we should just build ruby-trunk ourselves but that seems heavy for the CI.

**Comment by eregon** [comment]
You are right, we can merge this in the mean time until we figure it out for ruby-trunk.

Actually, I'm gladly surprised of the precision and extent of these specs, thanks for the great work @mjago!

**Comment by mjago** [comment]
Yes just looked again - [Yuki had a similar issue] (https://github.com/yuki24/did_you_mean/commit/322fe7026ec738f96de390d9ede447f65446cf56) which I guess is related.

**Comment by mjago** [comment]
Added an issue ruby/chkbuild/issues/29 to chkbuild regarding this

**Pull request merged**
