### PR TITLE
Wrong assumption

### PR DESCRIPTION
**Pull request by unak**
Platform dependent.

### CODE REVIEW

**Comment by eregon** [comment]
On which platform is it not the case?

**Comment by elia** [comment]
this could be related https://github.com/ruby/ruby/blob/trunk/test/ruby/test_string.rb#L2392-L2393

**Comment by unak** [comment]
>On which platform is it not the case?

64bit Windows.

**Comment by eregon** [comment]
@unak Ah, because pointers are still 32-bits (sounds strange) and fixnums are `long` so 64-bit? Or the opposite? Thanks for the patch!

**Comment by unak** [comment]
> @unak Ah, because pointers are still 32-bits (sounds strange) and fixnums are long so 64-bit? Or the opposite? Thanks for the patch!

The opposite.
64bit Windows is LLP64.  That is, fixnum(long)s are 32bits and pointers are 64bits.

**Pull request merged**
