### PR TITLE
try to fix missing libgmp

### PR DESCRIPTION
**Pull request by eregon**

### CODE REVIEW

**Comment by eregon** [comment]
@hsbt @nobu Do you know how we could fix https://travis-ci.org/ruby/spec/jobs/105398213? 
`gcc` on Travis seems to not find libgmp, even though it is installed (see `Installing APT Packages (BETA)`).
Should https://github.com/ruby/spec/blob/master/optional/capi/spec_helper.rb emit a different command? Or is it Travis' fault?

**Comment by hsbt** [comment]
I didn't investigate details.

But It caused to precompiled binary build by travis. In this case, buind environments have libgmp and linked it to ruby-head. but test environments can't find libgmp with test case.

**Comment by nobu** [comment]
Ubuntu seems to install `libgmp.so` at `/usr/lib/x86_64-linux-gnu`.

~~~
$ gcc -print-file-name=libgmp.so
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libgmp.so
~~~

`--enable-multiarch` configure option may help you.

**Comment by eregon** [comment]
Fixed by travis-ci/travis-ci#5560.

**Pull request closed without merging**
