### PR TITLE
Reenable sleep ns spec on MacOS

### PR DESCRIPTION
**Pull request by headius**
Investigating why this spec fails on MacOS in hopes of re-enabling it.

### CODE REVIEW

**Comment by headius** [comment]
This failure seems to be much more than just unreliability in `Kernel#sleep`. The test attempts to sleep 100 times for 0.1ms each time and confirm that the total time spent is between 10 and 30 ms. The logging I added shows that CRuby instead sleeps for anywhere from 89ms to over 350ms, on average an order-of-magnitude difference.

I'm attempting to disable parallel specs on MacOS to see if that helps this produce more reasonable results.

**Comment by herwinw** [comment]
FYI: #1213 has a change that improves the " Expected false == true" error message to show the actual values. Feel free to integrate that in your branch if that makes debugging easier.. Otherwise, I'll just leave that PR on Draft until this issue is fixed, to prevent adding another merge conflict.

**Comment by eregon** [comment]
Let's close, it doesn't even pass reliably on Linux

**Comment by headius** [comment]
Please don't close my PRs.

**Comment by headius** [comment]
@eregon I have made the change I suggested in https://github.com/ruby/spec/issues/1207#issuecomment-2463054050, removing the `< 0.03` check that caused the spec to be unpredictable on some combinations of Ruby and platform. I believe it should now reliably pass on all Ruby implementations that properly implement sub-millisecond sleep times.

**Review by eregon — APPROVED** [review]
Thanks, let's try this.

**Pull request merged**
