### PR TITLE
Import and integrate specs from rubysl-socket

### LINKED ISSUE #609: Importing specs from rubysl-socket
I plan to import specs from https://github.com/rubysl/rubysl-socket and merge them with the existing `socket` specs in ruby/spec. This should expand and improve the existing specs for the `socket` stdlib.

### PR DESCRIPTION
**Pull request by eregon**
Fixes #609.

### CODE REVIEW

**Comment by eregon** [comment]
@MSP-Greg Hello!
Could you take a look at this branch and run it locally? It now passes on Linux, but some specs hang on Windows or take a really long time, and some specs error or fail.

Unfortunately the feedback loop via AppVeyor is very slow and I have little knowledge about socket support on Windows.
If you have some time, could you try to add `platform_is_not :windows` guards, much like in the last commit f906115a380976df52c06ee2feffc368dc55cf91? (e.g. on your own fork of ruby/spec, then I can easily try it as well).

That would be far more efficient than me playing 10-min-per-ball ping pong with AppVeyor and guessing at best what doesn't work or hang on Windows :smiley:

**Comment by MSP-Greg** [comment]
@eregon Hello also...

> Could you take a look at this branch and run it locally?

Yes, a little later though.  And, yes, once I see what's going on, I can add some guards...

Greg

**Comment by MSP-Greg** [comment]
@eregon

This might take a while.  Attached is a 7z file (with a zip extension to make GitHub happy).  Wrote a script to loop thru the folders and generate a log of each.  The socket folder was the only one that locked/froze.

Briefly looking thru them, Windows Ruby doesn't support Unix sockets.  Recently doing work in the Puma repo, and some of the tests that rely on UnixSocket were disabled for both Windows & JRuby.  I'm not sure if there should a guard for UnixSocket?  FYI, MSFT is adding support for Unix sockets to Windows 10, but I'm not sure how far along it is.

Thanks, Greg

[spec_logs.7z.zip](https://github.com/ruby/spec/files/2196341/spec_logs.7z.zip)

**Comment by eregon** [comment]
@MSP-Greg Thank you!
Yes, Unix sockets are not expected to work on Windows for now, so we need to add guards there.
The new specs use a MSpec feature for this: `with_feature :unix_socket do ...`. The previous specs just use `platform_is_not :windows`. The feature is probably slightly better if Windows starts supporting Unix sockets at some point.

`Socket#accept using IPv4 using a bound socket that's not listening` seems to get stuck, it seems in general operations on unbound/not listening sockets just hang on Windows.

It also seems `Socket#shutdown` has no effect on Windows, maybe closing only the read or write end is not supported?

I'll add guards based on your logs, it seems only `socket/socket` specs hang so that's not so bad.

**Comment by MSP-Greg** [comment]
@eregon

>  The feature is probably slightly better

Agreed.  Do you need anything re `socket/socket`?

Re the two windows socket quirks, I haven't used anything similar, nor recall seeing anything similar.

Finally, I looked at Appveyor, and there have been a lot of trunk failures.  I'd be happy to look into that; any idea where to start?  A quick look seemed to show sometime after build 1314?

Thanks, Greg

**Comment by eregon** [comment]
> Do you need anything re socket/socket?

No, thanks, I think I should find the few hanging specs quickly enough as they all seem related.

> Finally, I looked at Appveyor, and there have been a lot of trunk failures. I'd be happy to look into that; any idea where to start? A quick look seemed to show sometime after build 1314?

That's a change by Koichi, to forbid `rb_enc_set_index` on arbitrary objects. He already fixed the specs in ruby/ruby, I would ignore failure on trunk until the next merge.
Really, it's not supported to run `ruby/spec` master on MRI trunk (I should probably just drop trunk in ruby/spec's CI), the specs in MRI's repository should be used instead as MRI trunk sometimes makes incompatible modifications.

**Comment by MSP-Greg** [comment]
@eregon

> Really, it's not supported to run `ruby/spec` master on MRI trunk

I assumed that, as in 'not really'.  For something like this, as long as there are up to date versions of trunk built, it's probably easier (and faster) than running them in `ruby/ruby`.  I had a look at `rubysl`, there's a lot of tests there...

**Comment by enebo** [comment]
@eregon I think you are correct that rubsl specs were just moved out of ruby/spec when rbx broke up their stdlib into rubsl-* gems.  The socket ones were added by Yorick Peterse after they found their new home (I think just for rubysl-socket?).

**Comment by MSP-Greg** [comment]
@eregon

Ran several times, seems stable, with two fails:

```
1)
Socket.getnameinfo using IPv4 using a 3 element Array as the first argument without custom flags returns an Array containing the hostname and service name FAILED
Expected "DESKTOP-DM0E9CF.Home"
 to equal "DESKTOP-DM0E9CF"

C:/Greg/GitHub/spec/library/socket/socket/getnameinfo_spec.rb:110:in `block (5 levels) in <top (required)>'
C:/Greg/GitHub/spec/library/socket/socket/getnameinfo_spec.rb:65:in `<top (required)>'

2)
Socket.getnameinfo using IPv6 using a 3 element Array as the first argument without custom flags returns an Array containing the hostname and service name FAILED
Expected "DESKTOP-DM0E9CF.Home"
 to equal "DESKTOP-DM0E9CF"

C:/Greg/GitHub/spec/library/socket/socket/getnameinfo_spec.rb:110:in `block (5 levels) in <top (required)>'
C:/Greg/GitHub/spec/library/socket/socket/getnameinfo_spec.rb:65:in `<top (required)>'
[/ | ==================100%================== | 00:00:00]      2F      0E

Finished in 8.016873 seconds

185 files, 1081 examples, 1686 expectations, 2 failures, 0 errors, 0 tagged

ruby 2.6.0dev (2018-07-17 trunk 63985) [x64-mingw32]
```

Re rubysl, I didn't really compare tests with the ones here.

Re testing, trunk, etc, I just meant that when one is adding a bunch (as opposed to a couple) of tests, testing here probably 'ruffles fewer feathers' than having it interfere with other commits passing in trunk...

Thanks again, Greg

**Comment by eregon** [comment]
@MSP-Greg Great, I relaxed the expectation for that spec, to use `should include`.

> Re testing, trunk, etc, I just meant that when one is adding a bunch (as opposed to a couple) of tests, testing here probably 'ruffles fewer feathers' than having it interfere with other commits passing in trunk...

Right, when adding a large number of specs it is preferable to add them here. Although I often add quite a few specs directly in TruffleRuby so I can test them directly in TruffleRuby's CI and that works fine too. Overall, it's quite rare different Ruby versions behave differently nowadays, most of the behavior is identical.

**Pull request merged**
