### PR TITLE
Add spec for Enumerator::Lazy#chunk

### PR DESCRIPTION
**Pull request by joshgelbard**
Mostly copied and slightly altered the existing specs that seemed most similar. Will do #chunk_while and company along the same lines unless this is wrong.

### CODE REVIEW

**Comment by joshgelbard** [comment]
It looks like the existing specs for Enumerator::Lazy all test for almost exactly the same things. Since I will otherwise shortly be adding four more files of that, I'm thinking of pulling out the shared tests into a shared examples group and using them with should_behave_like.

**Comment by eregon** [comment]
When possible, shared specs are indeed better so there is less duplication and examples added for one method also means added to others methods.
Could you try to make and use a shared spec for those?

The chunk_spec.rb files can then define a few `@ivar` like `@yieldsmixed` in the before :each block with the specific receiver class/method, and those can be used in the shared spec.
Or alternatively, they could just define a "factory" for creating a Enumerable/Enumerator::Lazy with the given elements, and the shared spec can use that.

**Comment by eregon** [comment]
@joshgelbard Did you have the occasion to look at sharing those specs?
If not, I'd rather merge this spec and then we can improve based on what's in `master`.

**Comment by eregon** [comment]
Let's merge this, thank you for the new spec!

**Pull request merged**
