### PR TITLE
[Ruby 2.5] String#casecmp? returns nil for non-string arguments

### PR DESCRIPTION
**Pull request by andrykonchin**
https://bugs.ruby-lang.org/issues/13312

### CODE REVIEW

**Comment by eregon** [comment]
That issue also talks about a similar think for `String#casecmp`, is that one already handled?

**Comment by andrykonchin** [comment]
@eregon yeah, it's already done in the same file

**Comment by stomar** [comment]
I'm not too deep into what the specs should or should not test, but I'm wondering about the specs for the TypeError: that behaviour seemed to be a bug and not something that should be spec'ed... (?)

**Comment by eregon** [comment]
@stomar Even though it is now recognized as a bug, it is still the behavior of Ruby 2.4 and before.
*In general*, we want specs for every behavior MRI exhibits, unless it's a VM bug/SEGV or deep implementation details. But it's sometimes hard to decide.
A simpler way to view this: other Ruby implementations want to be compatible with MRI, including the behavior of previous versions which might be a bit weird.
ruby/spec is not an "ideal" set of specs of Ruby, but specs of how MRI behaves, except parts that are MRI-only (basically only RubyVM).
When we find some strange behavior, we just file a bug on the MRI tracker but otherwise assume the behavior is intended and is therefore part of how MRI behaves and what users might rely on.

**Comment by stomar** [comment]
@eregon Thanks for the explanation.

**Pull request merged**
