### PR TITLE
Revert "DidYouMean specs for ruby 2.3"

### PR DESCRIPTION
**Pull request by mjago**
Reverts ruby/spec#351

Passing on Github.com/ruby/spec CI:
Travis 2.3.0p0
Appveyor 2.3.1p112
Failing on rubyci.org:
2.3.2p205

### CODE REVIEW

**Comment by mjago** [comment]
@eregon I reverted this since it broke rubyci big time.
 I presume it is related to the 2.4 issue we noticed.
I'll take a look later today.

**Comment by eregon** [comment]
This is strange, I would assume it would be fine on rubyci,org, because it does a `make install` and a fairly standard building of MRI.

**Comment by eregon** [comment]
Ah I found the reason, it's because `did_you_mean` and other gems are only installed by `make dist` which is run [after](http://rubyci.org/logs/rubyci.s3.amazonaws.com/ubuntu/ruby-2.3/log/20161109T035855Z.log.html.gz#dist) ruby/spec.
Maybe we should create an issue on https://github.com/ruby/chkbuild about this.

It might also be a sign that testing `did_you_mean` is more of an integration test than what ruby/spec usually does, and might be better done differently (e.g.: did_you_mean has its own tests and they should run as part of the implementation's testing process).

**Comment by mjago** [comment]
Ah OK - I got as far as seeing the gem is downloaded...
- r56569 ruby 2.3.2p205 (2016-11-05) [i686-linux] [2.3] (boron) 305W rubyspec:9F0E
``` sh
downloading bundled gem files…
…snip...
downloading did_you_mean-1.0.0.gem ... done
```
That makes sense 👍

**Comment by mjago** [comment]
Well the gem is very well unit-tested on github / travis and is a `bundled gem` etc.

It would also be possible to check for DidYouMean module before running tests ?

**Comment by eregon** [comment]
My concern is currently it seems only tested as a pair of last version/MRI trunk, but other combinations are not. I think like other "bundled libraries" (stdlib + bundled gems) it should be tested by Ruby implementations to make sure that part functions well.

**Comment by mjago** [comment]
Looking at [chkbuild/ruby.rb](https://github.com/ruby/chkbuild/blob/7ab436be8e70f9255cfea3237cef8ea0dd67d647/chkbuild/ruby.rb) I can't see any reason why spec testing happens before _completely building ruby_ - only that ruby/spec tests are grouped in the _do_test_ group . At the moment chkbuild only appears to check whether the bundled gems are download-able ? I am possibly missing something though:
[if do_test](https://github.com/ruby/chkbuild/blob/7ab436be8e70f9255cfea3237cef8ea0dd67d647/chkbuild/ruby.rb#L572)
[if use_rubyspec](https://github.com/ruby/chkbuild/blob/7ab436be8e70f9255cfea3237cef8ea0dd67d647/chkbuild/ruby.rb#L606-L607)

**Pull request merged**
