### PR TITLE
Add tests for method calls that have a space between method name and parentheses.

### PR DESCRIPTION
**Pull request by iliabylich**

### CODE REVIEW

**Comment by eregon** [comment]
This looks like it could be a parser limitation; do you know if it's intentional?

**Comment by iliabylich** [comment]
Yes, in fact `m ()` is not a method call without parameters. It's method call without parentheses that takes a single block argument (like wrapped with `begin;end`). It was made to resolve cases like:
``` ruby
m (a.nil? ? 1 : 0)
# (which is equivivalent to
arg = (a.nil? ? 1 : 0)
m arg
```

**Comment by iliabylich** [comment]
@eregon And you can pass only one parameter because it's not a regular parentheses, it's a block of code, you cant' write something like
``` ruby
a = (b + 1, c + 2)
```
Sometimes Ruby is weird :smile:

**Comment by eregon** [comment]
Thanks for explaining the rationale, makes sense now :)

**Pull request merged**
