### PR TITLE
Add jruby-head to TravisCI and allow it to fail

### PR DESCRIPTION
**Pull request by etehtsea**

### CODE REVIEW

**Comment by etehtsea** [comment]
Seems that jruby-head simply got stuck at some point. Will dig into this later.

**Comment by eregon** [comment]
This would be a nice idea but unfortunately it's more complicated.
We would need to import the tags from jruby as well at least.

The current process is I update the specs in jruby about once very month. This is not ideal for new specs since there is a time where it is not tested in JRuby's CI, but on the other hand allows to modify specs directly in the jruby copy which can be convenient at times.

If they are no modifications in jruby, it's much easier to update the specs, see https://github.com/ruby/spec/wiki/Merging-specs-from-JRuby-and-other-sources#3-merging-back-to-jruby.
Otherwise it's [quite a bit more involved](https://github.com/ruby/spec/wiki/Merging-specs-from-JRuby-and-other-sources) which I don't expect anyone to do but me.

**Comment by etehtsea** [comment]
@eregon idea is to not import tags from jruby just to see that compatibility with jruby is getting better over time (or worse).

**Comment by eregon** [comment]
@etehtsea The problem of Travis `allowed_failures` is I (and I would guess others) forget to look at the actual failures unless I am notified of it. This gets even worse if it's failing most of the time.
In that case we would need some mechanism to detect regressions. I am not sure it is worth it compared to using tags.
Some tags in JRuby are actually needed just to run the specs like `critical`. In an ideal world this wouldn't be needed (and maybe it's actually just a couple problematic specs) but it needs to be investigated.

**Comment by etehtsea** [comment]
Possibly specs that would never work on JRuby could be wrapped in something like `ruby_engine_is` guard.

**Comment by eregon** [comment]
I think it's more like some specs hanging due to jruby bugs, maybe we could have a try to give a timeout to specs.

**Comment by eregon** [comment]
Unfortunately, I think this is not going to work well.
* If we put it in `allowed_failures` we will never look into it and it will make the CI longer for no added value.
* If we make it part of the required jobs, then we would need some setup to get the corresponding tags. Adding a new spec that would fail on jruby might be fine if it's a bug of jruby, but would leave the CI failing until jruby tags it or fixes it. If it's unclear which implementation behaves well it must be discussed on MRI's bug tracker first anyway.

In other words, this is a test suite, and the most logical place to run it is within the implementation CIs. That way they can detect regressions, tag known failures, etc.
The fact we test MRI here is to make sure we do not add a spec that would not pass on the reference implementation (or report a bug if it behaves wrong).

On the other hand, it could be nice to have an overview of how much of ruby/spec each implementation passes. But this is an entirely different feature.

@etehtsea Since you are not the first to mention this (other impl should be tested here too), do you have any idea how I could communicate simply the rationale behind this choice? (cc @donv)
I am thinking maybe a link to the implementations CIs using ruby/spec could be helpful.

**Comment by eregon** [comment]
@headius Currently the failing new specs are noticed as new tags in jruby whenever I do the big spec merge. If we used a submodule (like Opal does) then it would be whenever it is updated, same thing.
I think maintaining this "update whenever you want" policy is critical for alternative implementations so they don't need to consistently care about new specs.

So I guess my point is, while it would be ideal to test new specs against other impls, most of the time we want the spec in even if an alternative impl would fail. And if the spec is truly buggy (I expect this to be more rare), then of course it can always be fixed here.

**Pull request closed without merging**
