### PR TITLE
Change tests for String#dump for UTF-8 to mostly fixed width upper-case

### PR DESCRIPTION
**Pull request by duerst**
Avoid brackets in \u escapes unless the number of hex digits is greater
than four; for four or less significant hex digits, always use four hex
digits, to align with Unicode convention. Also, use upper-case hex characters
rather than lower-case.

### CODE REVIEW

**Comment by duerst** [comment]
There should probably be some version guards around this change. Sorry I forgot them. I was surprised that a pull request worked even though there were conflicts. I'm still looking for a button or something that would allow me to update a forked project to catch up with the original.

**Comment by eregon** [comment]
It seems @nurse already fixed it in https://github.com/ruby/spec/commit/4f81c7791732d986973279f42a1989be97084a69. Thanks for the intention though.!
The best is usually to pull from `origin/master` before creating the commit, or rebase against it. Personally I never use a fork's `master` branch with git.

**Comment by nurse** [comment]
@duerst My fix, which includes version switch, will help your future changes.

**Comment by duerst** [comment]
@nurse Yui, thanks very much for your help!

**Pull request closed without merging**
