### PR TITLE
Add spec for date class

### PR DESCRIPTION
**Pull request by m-nakamura145**
added some specs for `Date` class.

* `Date#next`
* `Date#succ`

### CODE REVIEW

**Comment by stomar** [comment]
The specs could be a bit stronger and also include some „edge cases“, where the month or year changes. See e.g. #535.

**Comment by stomar** [comment]
BTW. I didn‘t check in the source code, but I would suppose these two methods are aliases.

**Comment by eregon** [comment]
@stomar Could you be the reviewer of this PR?
And then merge it when you think it's ready?

Indeed, they are aliases:
```ruby
> d=Date.today
=> #<Date: 2017-11-04 ((2458062j,0s,0n),+0s,2299161j)>
> d.method(:succ) == d.method(:next)
true
```
@m-nakamura145 So this means these specs should use a `shared: true` spec.

**Comment by stomar** [comment]
_(I hadn't noticed I'm a member for this repo.)_

@eregon I can review it, but since I'm not too familiar with specs for aliases, which I tried to figure out only recently, I would appreciate if you could first give me your ok for #538 and/or #539  :smile:.

**Comment by eregon** [comment]
@stomar Done, I'm sorry for the long wait, I was overwhelmed with reviews recently.

**Comment by eregon** [comment]
@m-nakamura145 Could you share these specs using `shared: true` (see examples in the codebase), and make them stronger as proposed in https://github.com/ruby/spec/pull/543#issuecomment-341637666 ?

**Comment by eregon** [comment]
@m-nakamura145 Why did you close the issue?
If it's too complicated to share these specs using `shared: true` or you don't have time to do, please tell so and we might be able to help.

**Pull request closed without merging**
