### PR TITLE
Stop to use invalid XML attribute name

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
I can't merge REXML 3.1.8 to the Ruby's repository without this change.
I want to merge REXML 3.1.8 into Ruby 2.6.0.

**Comment by eregon** [comment]
Hello,

It's enough to modify the synchronized copy of the specs under `spec/ruby` in `ruby/ruby`, as you did in https://github.com/ruby/ruby/commit/0d1abb904e9eda11dfed19181553725764a3d950#diff-c0cb2ff282611da247a0e8daf0654fcd
I will then propagate the change here when I synchronize repositories monthly (around New Year).

I will merge this PR since it's same change and you opened the PR, but there is no need to make a PR here (unless you want to discuss changes), it's enough to change in `ruby/ruby` :smiley:

**Comment by kou** [comment]
Oh, I got it. Sorry for bothering you.

**Comment by eregon** [comment]
No worry :smiley:

**Pull request merged**
