### PR TITLE
Don't escape tilde in #url_encode

### PR DESCRIPTION
**Pull request by k0kubun**
https://bugs.ruby-lang.org/issues/6696

Fix for https://github.com/ruby/ruby/commit/53127c2410c29f7cc942a76baa7be97ba65aafda and https://github.com/ruby/ruby/commit/e1b432754553423008a14d39d0901eabc99e7ddb.

### CODE REVIEW

**Comment by eregon** [comment]
See https://github.com/ruby/ruby/blob/trunk/spec/README.md for more info.

**Comment by k0kubun** [comment]
> Since you are a MRI committer, please commit this under MRI's ruby/spec copy in spec/rubyspec so MRI's CI can be fixed directly.
> 
> See https://github.com/ruby/ruby/blob/trunk/spec/README.md for more info.

Thank you for the information! Fixed https://github.com/ruby/ruby/commit/29a26009947cdde301cf7b1cc80decdb4cc04ca1.

**Comment by k0kubun** [comment]
It seems that Travis ruby-head is failing because r58763 is used. It'll pass after r58773.

**Comment by eregon** [comment]
Great, thanks!

Please add as well the new specs in `ruby_version_is` guards in MRI spec/rubyspec,
it helps to see what changed and confirm the behavior changed as expected in those Ruby versions.
In other words, MRI spec/rubyspec is merged regularly with this repo, and this repo tests not only ruby-trunk but every ruby since 2.2 and other Ruby implementations.

**Comment by eregon** [comment]
I'll close this pull request as your commits in ruby/ruby will get merged here when I extract the commits from MRI spec/rubyspec (I do that about once every month).

**Comment by k0kubun** [comment]
> Please add as well the new specs with ruby_version_is guards in MRI spec/rubyspec,
it helps to see what changed and confirm the behavior changed as expected in those Ruby versions.
In other words, MRI spec/rubyspec is merged regularly with this repo, and this repo tests not only ruby-trunk but every ruby since 2.2 and other Ruby implementations.

Oh I see. So I'll commit exactly the same change in MRI too. Just a moment please.

**Comment by k0kubun** [comment]
Done https://github.com/ruby/ruby/commit/d06a7cfeddc376fdf6150e5bc409c6e507ede068. Thank you for your help!

**Comment by eregon** [comment]
Thanks a lot!

**Pull request closed without merging**
