### PR TITLE
add specs for 2.4+ behavior on duping numerics,nil,false and true

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by eregon** [comment]
Thank you for the new specs, they look perfect!

**Comment by marcandre** [comment]
Good job!
FYI, I tweaked some of these in 1153e301087befe041fbfb7c58676b8bd8969dc0
Also fixed the whitespace, best to config your editor for 2 spaces per indent.
Thanks for the specs.

**Comment by eregon** [comment]
@marcandre Thank you for the fixes!

**Comment by doudou** [comment]
> Also fixed the whitespace, best to config your editor for 2 spaces per indent.

@marcandre oh sorry for that ... I'll keep it in mind next time. Our standard here is 4 spaces ...

**Pull request merged**
