### PR TITLE
Add specs for multiple assignment to constants

### PR DESCRIPTION
**Pull request by vais**
Re: https://github.com/opal/opal/pull/1350

### CODE REVIEW

**Comment by mame** [comment]
Thank you, I was about to start writing the same spec :-)

**Comment by vais** [comment]
@mame LOL, you can still write the spec for https://github.com/opal/opal/pull/1351 - I don't think I'll be able to get to that one :smile:

In other news, the build failed on Travis CI even though all specs ran fine on my machine. Investigating now... (constants are tricky)

**Comment by vais** [comment]
@mame @eregon using `A` and `B` constants did the trick (for some reason using a `C` constant broke other specs on Travis last time). Please merge if you think this is ok, otherwise LMK if you have other suggestions on how to scope constants to specs...

**Comment by eregon** [comment]
@vais One way would be to use nested constants, like
`VariablesSpecs::A, VariablesSpecs::B = 1, 2` (could also be `mod = Module.new; mod::A`).
But this is actually another case and does not use lexical scoping.

So instead, to be able to use lexical constant scoping, maybe we could just wrap these constants accesses in:
```ruby
    it "assigns constants" do
      module VariableSpecs
        A, B = 1
        [A, B].should == [1, nil]
      end
    end
```

What do you think? Some other specs seem to do the same.
This would solve the global namespace (Object) pollution problem.
Could you update the specs to use this style?

**Comment by vais** [comment]
Thanks, @eregon!

**Comment by eregon** [comment]
Looks awesome, thanks @vais!
The new naming also helps to identify quicker what is tested :smiley:

**Comment by vais** [comment]
:beers:

**Pull request merged**
