### PR TITLE
No CAPI signature files

### PR DESCRIPTION
**Pull request by nobu**
Do not create CAPI signature files which are not needed since
d9e3e4d2.

### CODE REVIEW

**Comment by eregon** [comment]
Will this recompile if we are using different implementations or different versions of MRI?

**Comment by nobu** [comment]
In the case running at the `spec` source directory?
I think it should use separate directories for each implementations/versions.

**Comment by eregon** [comment]
Yes, in the case of running in the git checkout.
Multiple directories would be a fix, although it would leave some files behind.
Currently it uses the same directory for all implementations: `spec/rubyspec/optional/capi/ext/`.

So I cannot merge as-is as it would break running with multiple MRI versions and other implementations with the same checkout.
Why do you want to remove signature files actually?
I agree that a design with separate directories would be nicer, so if you do that I'll be happy to merge :)

**Comment by nobu** [comment]
As I usually run rubyspec from ruby's build directories, for each targets (platforms, compilers, and `configure` options), haven't considered that case.
We need the way to direct separate directories first, and I close this for now.

**Comment by eregon** [comment]
@nobu OK, I'll do the directory separation, should be simple.

**Comment by eregon** [comment]
I did the change in 31252bd8bb2ed68300efe743af2a56b81442e272, I'll reopen and try to merge this then.

**Comment by eregon** [comment]
I chose rubyspec/ext/RUBY_NAME/RUBY_VERSION as `objdir`, is that OK?

**Comment by eregon** [comment]
@nobu merged, thanks for the fix and the idea!

**Comment by nobu** [comment]
It doesn't seem good for MRI `make test-rubyspec`, because the `objdir` would be created under the `rubyspec` source directory.
I often mount the source directories read-only, so it would fail.
Probably something to override the default `objdir` may be nice.

**Comment by nobu** [comment]
And only `RUBY_VERSION` is not enough but `RUBY_PLATFORM` will be needed too.

**Comment by eregon** [comment]
> And only RUBY_VERSION is not enough but RUBY_PLATFORM will be needed too.

It's not very common to run ruby with different RUBY_PLATFORM from the same checkout though, isn't it?

> It doesn't seem good for MRI make test-rubyspec, because the objdir would be created under the rubyspec source directory.
I often mount the source directories read-only, so it would fail.
Probably something to override the default objdir may be nice.

I see, how would you like to do that, an environment variable (`SPEC_OBJ_DIR`?) or some other setting set by default in MRI's mspec config?

**Comment by nobu** [comment]
> It's not very common to run ruby with different RUBY_PLATFORM from the same checkout though, isn't it?

Maybe.

> I see, how would you like to do that, an environment variable (SPEC_OBJ_DIR?) or some other setting set by default in MRI's mspec config?

I prefer a command line option, but mspec does not provide a way to add an option from a spec file?
Then an environment variable is ok.

**Comment by nobu** [comment]
Or, just that global variable?

```diff
diff --git a/optional/capi/spec_helper.rb b/optional/capi/spec_helper.rb
index 9ecaede..e72e666 100644
--- a/optional/capi/spec_helper.rb
+++ b/optional/capi/spec_helper.rb
@@ -4,8 +4,7 @@ $extmk = false
 require 'rbconfig'
 require 'fileutils'
 
-rootdir = File.expand_path('../../..', __FILE__)
-OBJDIR = "#{rootdir}/ext/#{RUBY_NAME}/#{RUBY_VERSION}"
+OBJDIR ||= File.expand_path("../../../ext/#{RUBY_NAME}/#{RUBY_VERSION}", __FILE__)
 FileUtils.makedirs(OBJDIR)
 
 def extension_path
```
and in MRI,

```diff
diff --git a/spec/default.mspec b/spec/default.mspec
index 60ceaf3..f9392e6 100644
--- a/spec/default.mspec
+++ b/spec/default.mspec
@@ -1,6 +1,7 @@
 # -*- ruby -*-
 load "./rbconfig.rb"
 load File.dirname(__FILE__) + '/rubyspec/default.mspec'
+OBJDIR = File.expand_path("spec/rubyspec/optional/capi/ext")
 class MSpecScript
   builddir = Dir.pwd
   srcdir = ENV['SRCDIR']
```

**Comment by nobu** [comment]
See #247.

**Comment by eregon** [comment]
How does it work if the whole ruby checkout is read-only?
Is there a symlink from `spec` to some rw directory?

**Comment by nobu** [comment]
The current working directory, which is the build directory, must be writable, of course.
The source directory is given as the part of the script, `$srcdir/configure`.

**Comment by eregon** [comment]
Ah, right, since there is only 1 argument to expand_path, it expands relative to the current (build) directory, thanks for the explanation.

**Pull request merged**
