### PR TITLE
Import Socket::Option specs from rubysl-socket

### PR DESCRIPTION
**Pull request by etehtsea**
This specs are originally authored by @YorickPeterse and licensed by BSD
license.

### CODE REVIEW

**Comment by eregon** [comment]
@etehtsea @YorickPeterse ruby/spec is licensed as MIT, do you agree to re-license those specs with the MIT license?

**Comment by YorickPeterse** [comment]
@eregon The specs are licensed under the BSD license. Including the BSD license somewhere should suffice.

**Comment by etehtsea** [comment]
@eregon @YorickPeterse @eregon I added license inside each spec file.

**Comment by etehtsea** [comment]
I've found that there was option specs. 
https://github.com/ruby/spec/commit/cc39ba516cfeb71416d81c8f093f4fc3199b0775
https://github.com/ruby/spec/commit/9709120a63ac08873cb6e6f8ade3533f7530bcee

**Comment by eregon** [comment]
@etehtsea Thanks for the investigation!
The license per header seems a good option.
I'll have a look tomorrow, not sure why those specs disappeared since I thought I kept the files removed by that commit, maybe something missed in the merge.

**Comment by eregon** [comment]
@etehtsea So indeed a few specs were lost, I added them back in f305537c777a191fc102efaddfccc37825af2056.
The specs look very similar, but it would be good to add the missing parts in the existing ones.
I'll look at that tomorrow.

**Comment by etehtsea** [comment]
@eregon good, thanks!

**Comment by headius** [comment]
@YorickPeterse The original socket specs, under the rubyspec project, were not licensed BSD. I believe they were MIT licensed. I know you have added a lot and cleaned up many specs. Did you rewrite all of them from scratch?

If you did your additions and modifications atop the older rubyspec code, I have to also ask: did you contact everyone who contributed to those specs and get their permission to relicense as BSD?

**Comment by headius** [comment]
A bit of clarification... I believe MIT is permissive enough that you can *add* BSD, but I don't think you can *remove* MIT without getting permission from all former contributors.

**Comment by YorickPeterse** [comment]
@headius As far as I can remember I re-wrote all specs from scratch.

**Pull request closed without merging**
