### PR TITLE
Reset $, global variable back to nil to prevent IO.print from breaking.

### LINKED ISSUE #194: Leaving "$," gvar value can pollute a global test suite
[This](https://github.com/ruby/spec/blob/master/language/predefined_spec.rb#L633) test doesn't restore the value of `$,` back to nil. `IO.print` uses it internally for joining passed strings into a single one. If interpreter allows to set this global variable, the whole test suite breaks.

### PR DESCRIPTION
**Pull request by iliabylich**
Fixes #194

### CODE REVIEW

**Comment by elia** [comment]
@iliabylich can you use before/after instead of begin/ensure?

eg. https://github.com/iliabylich/rubyspec/blob/reset-dollar-comma-gvar-back-to-nil/language/predefined_spec.rb#L581-L589

**Comment by iliabylich** [comment]
Done

**Comment by elia** [comment]
@iliabylich great thanks, I'll merge when CI finishes. 

@eregon hope this is fine (vs. assigning an ivar in a `before` and restoring in an `after`)

**Comment by eregon** [comment]
Looks great, I'll let you merge @elia !

**Comment by elia** [comment]
ha! thanks man :beers: :smile:

**Comment by eregon** [comment]
Thanks @iliabylich for fixing this!

**Pull request merged**
