### PR TITLE
Add chomp specs for StringIO#gets, StringIO#readline, StringIO#each_l…

### PR DESCRIPTION
**Pull request by charle692**
…ine, StringIO#readlines, StringIO#each and StringIO#lines

Addresses part of #473.

### CODE REVIEW

**Comment by eregon** [comment]
This looks great, thank you!
Could you replace `carriage returns` by `newline characters`, as in #503?

**Comment by charle692** [comment]
Ok sorry about that, I will work on that as soon as I get home from work.

**Comment by charle692** [comment]
@eregon Made the requested changes. Let me know if there's anything else that needs done.

**Comment by eregon** [comment]
@charle692 Thank you for the new specs!

**Pull request merged**
